name: Create a comment on new issues

on:
  issues:
    types: [opened]
  
jobs:
  comment-with-action:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
        shell: bash
  
  comment-with-api:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment with API
        run: | 
          gh api -X POST \
            http://api.github.com/repo/${ORGANIZATION}/${REPOSITORY}/issues/${ISSUE_NUMBER/comments \
            -f body='
            Comment but from the API call not action
            '
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            ORGANIZATION: ${{ github.event.organisation.login }}
            REPOSITORY: ${{ github.event.repository.name }}
            ISSUE_NUMBER: ${{ github.event.issue.number }}
  
